/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../../../backend-api/src/modules/auth/controller`; params?: Router.UnknownInputParams; } | { pathname: `/../../../backend-api/src/modules/auth/routes.test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/events`; params?: Router.UnknownInputParams; } | { pathname: `/teams`; params?: Router.UnknownInputParams; } | { pathname: `/events/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/run/[eventId]`, params: Router.UnknownInputParams & { eventId: string | number; } } | { pathname: `/teams/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../backend-api/src/modules/auth/controller`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../backend-api/src/modules/auth/routes.test`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/events`; params?: Router.UnknownOutputParams; } | { pathname: `/teams`; params?: Router.UnknownOutputParams; } | { pathname: `/events/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/run/[eventId]`, params: Router.UnknownOutputParams & { eventId: string; } } | { pathname: `/teams/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/feed${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../../../backend-api/src/modules/auth/controller${`?${string}` | `#${string}` | ''}` | `/../../../backend-api/src/modules/auth/routes.test${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/events${`?${string}` | `#${string}` | ''}` | `/teams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../../../backend-api/src/modules/auth/controller`; params?: Router.UnknownInputParams; } | { pathname: `/../../../backend-api/src/modules/auth/routes.test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/events`; params?: Router.UnknownInputParams; } | { pathname: `/teams`; params?: Router.UnknownInputParams; } | `/events/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/run/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/teams/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/events/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/run/[eventId]`, params: Router.UnknownInputParams & { eventId: string | number; } } | { pathname: `/teams/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
